version: '{build}-{branch}'
image: Visual Studio 2017
configuration: Release
environment:
  root_dir: '%APPVEYOR_BUILD_FOLDER%'
  solution_dir: '%root_dir%\src'
  project_name: Contrib.System.Printing.Xps
install:
- cmd: choco install packages.config -y
before_build:
- cmd: nuget restore "%solution_dir%\%project_name%.sln"
- cmd: gitversion /output buildserver /updateAssemblyInfo
build:
  project: '%solution_dir%\%project_name%.sln'
after_build:
- cmd: nuget pack "%solution_dir%\%project_name%\%project_name%.csproj" -properties "Configuration=%configuration%" -symbols
- cmd: appveyor PushArtifact "%root_dir%\%project_name%.%GitVersion_NuGetVersionV2%.nupkg"
- cmd: appveyor PushArtifact "%root_dir%\%project_name%.%GitVersion_NuGetVersionV2%.symbols.nupkg"
deploy:
- provider: NuGet
  name: MyGet
  server: https://www.myget.org/F/dittodhole/api/v2/package
  api_key:
    secure: c9r6oyxFOqnfj0xezZcLIoopgoBUb5ib9nrTYMkXDTqzvMrrXmprbHgyldag6NZ4
  symbol_server: https://www.myget.org/F/dittodhole/symbols/api/v2/package
  on:
    branch: develop
- provider: NuGet
  name: NuGet
  api_key:
    secure: bP+3+r6NPoiV1kVeM/5x4OPM2p7p0zJXeV9E1wKoEAMtIhhi7+HRVycNsa8v1Ujc
  on:
    branch: master
- provider: NuGet
  name: NuGet (pre release)
  api_key:
    secure: bP+3+r6NPoiV1kVeM/5x4OPM2p7p0zJXeV9E1wKoEAMtIhhi7+HRVycNsa8v1Ujc
  on:
    branch: /release\/.*/