//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contrib.System.Printing.Xps.Tests.ExtensionMethods {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XpsPrintCapabilitiesExtensionsTests_PrintCapabilities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XpsPrintCapabilitiesExtensionsTests_PrintCapabilities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contrib.System.Printing.Xps.Tests.ExtensionMethods.XpsPrintCapabilitiesExtensions" +
                            "Tests.PrintCapabilities", typeof(XpsPrintCapabilitiesExtensionsTests_PrintCapabilities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.microsoft.com/windows/printing/oemdriverpt/Datamax_O_Neil_E_4204B_Mark_III_7_3_4_0_&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot;&gt;
        ///  &lt;psf:Feature name=&quot;psk:PageOutputColor&quot;&gt;
        ///    &lt;psf:Property name=&quot;psf:SelectionType&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Datamax_O_Neil_E_4204B_Mark_III {
            get {
                return ResourceManager.GetString("Datamax-O\'Neil E-4204B Mark III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.microsoft.com/windows/printing/oemdriverpt/Microsoft_Shared_Fax_Driver_6_1_7601_17514_&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot;&gt;
        ///  &lt;psf:Feature name=&quot;psk:PageOutputColor&quot;&gt;
        ///    &lt;psf:Property name=&quot;psf:SelectionType&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.microsoft.com/windows/printing/oemdriverpt/Foxit_PhantomPDF_Printer_Driver_6_0_0_0_&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot;&gt;
        ///  &lt;psf:Feature name=&quot;psk:PageOutputColor&quot;&gt;
        ///    &lt;psf:Property name=&quot;psf:SelectionType&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Foxit_PhantomPDF_Printer {
            get {
                return ResourceManager.GetString("Foxit PhantomPDF Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot; xmlns:hpps=&quot;http://schemas.hp.com/printers/common/v.1.0&quot;&gt;
        ///  &lt;psf:Feature name=&quot;psk:PageOrientation&quot;&gt;
        ///    &lt;psf:Property name=&quot;psf:SelectionType&quot;&gt;
        ///      &lt;psf:Value xsi:type=&quot;xsd:QName&quot;&gt;psk:PickOne&lt;/psf:Va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HP_ePrint {
            get {
                return ResourceManager.GetString("HP ePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.lexmark.com/windows/2007/01/printing/printschemakeywords&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot;&gt;
        ///  &lt;psf:Feature name=&quot;psk:PageICMRenderingIntent&quot;&gt;
        ///    &lt;psf:Property name=&quot;psf:SelectionType&quot;&gt;
        ///      &lt;psf:Value xsi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lexmark_X790_Series {
            get {
                return ResourceManager.GetString("Lexmark X790 Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.microsoft.com/windows/printing/oemdriverpt/Microsoft_Print To PDF/10.0.10240.17797/&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot; xmlns:ns0001=&quot;http://schemas.microsoft.com/windows/2015/02/printing/printschemakeywords/mic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Print_to_PDF {
            get {
                return ResourceManager.GetString("Microsoft Print to PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.microsoft.com/windows/2006/06/printing/printschemakeywords/microsoftxpsdocumentwriter&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot;&gt;
        ///  &lt;psf:ParameterDef name=&quot;psk:JobCopiesAllDocuments&quot;&gt;
        ///    &lt;psf:Property name=&quot;psf:Data [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_XPS_Document_Writer {
            get {
                return ResourceManager.GetString("Microsoft XPS Document Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.microsoft.com/windows/printing/oemdriverpt/PDF_Architect 6 Driver/4.9.25.2/&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot;&gt;
        ///  &lt;psf:Feature name=&quot;psk:PageOutputColor&quot;&gt;
        ///    &lt;psf:Property name=&quot;psf:SelectionType&quot;&gt;
        ///      &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PDF_Architect_6 {
            get {
                return ResourceManager.GetString("PDF Architect 6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.microsoft.com/windows/printing/oemdriverpt/Send_to_Microsoft_OneNote_15_Driver_6_1_7601_17514_&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot;&gt;
        ///  &lt;psf:ParameterDef name=&quot;psk:JobCopiesAllDocuments&quot;&gt;
        ///    &lt;psf:Property name= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Send_To_OneNote_2013 {
            get {
                return ResourceManager.GetString("Send To OneNote 2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.microsoft.com/windows/printing/oemdriverpt/Send_to_Microsoft_OneNote_16_Driver_10_0_10240_17797_&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot;&gt;
        ///  &lt;psf:ParameterDef name=&quot;psk:JobCopiesAllDocuments&quot;&gt;
        ///    &lt;psf:Property nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Send_To_OneNote_2016 {
            get {
                return ResourceManager.GetString("Send To OneNote 2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;psf:PrintCapabilities xmlns:psf=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemaframework&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1&quot; xmlns:ns0000=&quot;http://schemas.microsoft.com/windows/printing/oemdriverpt/Zebra_ZP 450 CTP/7.4.2.0/&quot; xmlns:psk=&quot;http://schemas.microsoft.com/windows/2003/08/printing/printschemakeywords&quot;&gt;
        ///  &lt;psf:Feature name=&quot;psk:PageOutputColor&quot;&gt;
        ///    &lt;psf:Property name=&quot;psf:SelectionType&quot;&gt;
        ///      &lt;psf:Valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zebra_ZP_450_CTP {
            get {
                return ResourceManager.GetString("Zebra ZP 450 CTP", resourceCulture);
            }
        }
    }
}
